version: "2"
services:
  api-server:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/notes_example
      - PORT=3001
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
